services:
  - type: web
    name: chemical-visualizer-backend
    env: python
    rootDir: chemical_visualizer/backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py create_default_user"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_CORS_ORIGINS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
    autoDeploy: true
